version: "3.9"

services:

  # docker run \
  #    -it \
  #    --rm \
  #    -v ${PWD}:/app \
  #    -v /app/node_modules \
  #    -p 3001:3000 \
  #    -e CHOKIDAR_USEPOLLING=true \
  #    oleksiivelychko/react-client
  react-client:
    container_name: react-client
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: oleksiivelychko/react-client
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true


